version: '3.4'

services:
  application.apicalculajuros:
    image: ${DOCKER_REGISTRY-}applicationapicalculajuros
    build:
      context: .
      dockerfile: src/Application/Application.ApiCalculaJuros/Dockerfile
    ports:
        - "501:80"

  application.apitaxadejuros:
    container_name: apitaxadejuros
    image: ${DOCKER_REGISTRY-}applicationapitaxadejuros
    build:
      context: .
      dockerfile: src/Application/Application.ApiTaxaDeJuros/Dockerfile
    ports:
         - "502:80"
  